name: GPG Debug

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Secret Value
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}"

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: public key output
        run: gpg -a --export ${{ secrets.GPG_KEY_ID }}

      - name: pwd
        run: pwd

      - name: ls
        run: ls

      - name: Check GPG version
        run: gpg --version

      - name: List existing GPG keys
        run: |
          echo "== Secret Keys =="
          gpg --list-secret-keys || true
          echo "== Public Keys =="
          gpg --list-keys || true

      - name: Setup Maven settings
        env:
          MVN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MVN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mkdir -p ~/.m2
          envsubst < .github/settings.xml > ~/.m2/settings.xml

      - name: deploy
        run: mvn deploy
